 //from mobileopencraft
 blocks[0]=new Point(-1, -1);
 blocks[1]=new Point(1, 0); // Rock
 blocks[2]=new Point(0, 0); // Grass
 blocks[3]=new Point(2, 0); // Dirt
 blocks[4]=new Point(0, 1); // Cobblestone
 blocks[5]=new Point(4, 0); // Planks
 blocks[6]=new Point(15, 0); // Shrub
 blocks[7]=new Point(1, 1); // Adminium
 blocks[8]=new Point(13, 12); // Water
 blocks[9]=new Point(13, 12); // Still Water
 blocks[10]=new Point(13, 14); // Lava
 blocks[11]=new Point(13, 14); // Still Lava
 blocks[12]=new Point(2, 1); // Sand
 blocks[13]=new Point(3, 1); // Gravel
 blocks[14]=new Point(0, 2); // Ore Gold
 blocks[15]=new Point(1, 2); // Ore Iron
 blocks[16]=new Point(1, 2); // Ore Coal
 blocks[17]=new Point(4, 1); // Trunk
 blocks[18]=new Point(4, 3); // Leaves
 blocks[19]=new Point(0, 3); // Sponge
 blocks[20]=new Point(1, 3); // Glass
 blocks[21]=new Point(1, 8); // Cloth Red
 blocks[22]=new Point(2, 13); // Cloth Orange
 blocks[23]=new Point(0, 4); // Cloth Yellow
 blocks[24]=new Point(0, 4); // Cloth YellowGreen
 blocks[25]=new Point(0, 4); // Cloth Green
 blocks[26]=new Point(0, 4); // Cloth GreenBlue
 blocks[27]=new Point(1, 13); // Cloth Cyan
 blocks[28]=new Point(0, 4); // Cloth LightBlue
 blocks[29]=new Point(0, 4); // Cloth Blue
 blocks[30]=new Point(0, 4); // Cloth Purple
 blocks[31]=new Point(0, 4); // Cloth Indigo
 blocks[32]=new Point(0, 4); // Cloth Violet
 blocks[33]=new Point(0, 4); // Cloth Pink
 blocks[34]=new Point(1, 7); // Cloth DarkGray
 blocks[35]=new Point(2, 7); // Cloth Gray
 blocks[36]=new Point(0, 4); // Cloth White
 blocks[37]=new Point(12, 0); // Flower Yellow
 blocks[38]=new Point(13, 0); // Flower Red
 blocks[39]=new Point(13, 1); // Mushroom Brown
 blocks[40]=new Point(12, 1); // Mushroom Red
 blocks[41]=new Point(7, 1); // Block Gold
 blocks[42]=new Point(6, 1); // Block Iron
 blocks[43]=new Point(5, 0); // Stair Double
 blocks[44]=new Point(6, 0); // Stair Half
 blocks[45]=new Point(7, 0); // Brick Red
 blocks[46]=new Point(8, 0); // Dynamite
 blocks[47]=new Point(3, 2); // Bookcase
 blocks[48]=new Point(4, 2); // Mossey Cobblestone
 blocks[49]=new Point(5, 2); // Obsidian

